version: '3.9'

services:
  web:
    build:
      context: .
      target: development
    command: npm run dev
    ports:
      - '6000:3000'
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules

volumes:
  node_modules:
