version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    command: rails server -b '0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - type: volume
        source: bundle_cache
        target: /usr/local/bundle
      - type: bind
        source: ./api
        target: /myapp
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://myappuser:password@db/openapi_sample_api_development

  db:
    image: postgres:13.10
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openapi_sample_api_development

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    ports:
      - '6000:3000'
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules

volumes:
  bundle_cache:
  db_data:
  node_modules:
