version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    command: rails server -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - type: volume
        source: bundle_cache
        target: /usr/local/bundle
      - type: bind
        source: ./
        target: /myapp
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://myappuser:myapppassword@db/myapp_development

  db:
    image: postgres:15
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=myapppassword
      - POSTGRES_DB=myapp_development

volumes:
  bundle_cache:
  db_data:
